//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticalServicelevelMatrix
    {
        public string Metal { get; set; }
        public string TotalInflow { get; set; }
        public string TotalResolved { get; set; }
        public string MarchResponse { get; set; }
        public string Resolution { get; set; }
        public string ApplicationAvailability { get; set; }
        public string Batcheffectiveness { get; set; }
        public string SyntheticTransactionResponseTime { get; set; }
        public string SHI { get; set; }
        public string RCA { get; set; }
    }
}
