//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSL_table
    {
        public string Tower { get; set; }
        public Nullable<int> AsOfYear { get; set; }
        public Nullable<int> AsOfMonth { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Metal { get; set; }
    }
}
