//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSL_Summary
    {
        public string Category { get; set; }
        public Nullable<double> Target { get; set; }
        public Nullable<double> Jan { get; set; }
        public Nullable<double> Feb { get; set; }
        public Nullable<double> Mar { get; set; }
    }
}
