//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSLInference
    {
        public string Category { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public string Status { get; set; }
        public int CommentID { get; set; }
    }
}
