//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSLTowerLevelDetailsforMonth
    {
        public string Category { get; set; }
        public string Target { get; set; }
        public string CoreSystem { get; set; }
        public string CorporateSystems { get; set; }
        public string CustomerInteraction { get; set; }
        public string InformationManagement { get; set; }
        public string ThirdPartyIntegration { get; set; }
    }
}
