//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentFeedSummary
    {
        public string Tower { get; set; }
        public Nullable<int> Inflow { get; set; }
        public Nullable<int> Resolved { get; set; }
        public Nullable<int> ResolutionSLA { get; set; }
        public Nullable<int> ResponseSLA { get; set; }
        public Nullable<int> Backlog { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MM { get; set; }
        public Nullable<int> Breached { get; set; }
        public Nullable<int> WIP { get; set; }
        public string IncidentPriority { get; set; }
        public string Metal { get; set; }
        public string Tier { get; set; }
        public Nullable<int> AsOfMonth { get; set; }
        public Nullable<int> AsOfYear { get; set; }
    }
}
