//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_summary
    {
        public string Tower { get; set; }
        public Nullable<int> TotalIncidents { get; set; }
        public string TotalResolvedandpercenttoTotal { get; set; }
        public string TotalResolutionSLA { get; set; }
        public Nullable<int> AgingDays3 { get; set; }
        public Nullable<int> AgingDaysgreaterthan3 { get; set; }
        public Nullable<int> AgingDaysgreaterthan7 { get; set; }
        public Nullable<int> AgingDaysgreaterthan10 { get; set; }
        public Nullable<int> AgingTotal { get; set; }
        public Nullable<int> TotalMarInflow { get; set; }
    }
}
