//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCA
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string RCA_State { get; set; }
        public string RCA_Priority { get; set; }
        public string ParentIncident { get; set; }
        public string ParentIncident_State { get; set; }
        public string ProblemTicket { get; set; }
        public string RCA_Status { get; set; }
        public string ProblemTicketOpenDate { get; set; }
        public string SLABreach { get; set; }
        public string Comments { get; set; }
        public string Parent_IncidentPriority { get; set; }
        public string AssignmentGroup { get; set; }
        public string AssignedTo { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string ServiceOffering { get; set; }
        public Nullable<System.DateTime> Opened { get; set; }
        public string Openedby { get; set; }
        public string Metal { get; set; }
        public string tower { get; set; }
        public Nullable<int> AsOfMonth { get; set; }
        public Nullable<int> AsOfYear { get; set; }
        public Nullable<int> SLAMet { get; set; }
    }
}
