//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryPeriod
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> MM { get; set; }
        public string Mon { get; set; }
        public Nullable<int> Week { get; set; }
        public int Id { get; set; }
    }
}
