//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synthetic_Trans
    {
        public int Id { get; set; }
        public string Transactions { get; set; }
        public Nullable<double> TargetInSecs { get; set; }
        public Nullable<double> ActualInSecs { get; set; }
        public string SyntheticTrans_Met { get; set; }
        public Nullable<int> AsOfMonth { get; set; }
        public Nullable<int> AsOfYear { get; set; }
        public string tower { get; set; }
    }
}
