//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActionItem
    {
        public int Sno { get; set; }
        public string Action_Item { get; set; }
        public string Owner { get; set; }
        public string ETA { get; set; }
        public string Status { get; set; }
    }
}
