//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProblemSummary
    {
        public string Summary { get; set; }
        public Nullable<int> Nov2015 { get; set; }
        public Nullable<int> Dec2015 { get; set; }
        public Nullable<int> Jan2016 { get; set; }
        public Nullable<int> Feb2016 { get; set; }
        public Nullable<int> Mar2016 { get; set; }
    }
}
