//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tower2
    {
        public string Tower { get; set; }
        public string Active { get; set; }
        public string linecolor { get; set; }
        public string tower_alias { get; set; }
    }
}
