//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnResolvedIncident
    {
        public string Tower { get; set; }
        public string PendingChange { get; set; }
        public string PendingUser { get; set; }
        public string PendingValidation { get; set; }
        public string PendingVendor { get; set; }
        public string WorkInProgress { get; set; }
        public string GrandTotal { get; set; }
    }
}
